site_name: Central Docs
site_url: https://city-of-saint-louis.github.io/central-docs/
repo_url: https://github.com/city-of-saint-louis/central-docs
repo_name: /central-docs
theme: 
  name: material
  favicon: assets/bookshelf.svg
  icon:
    logo: material/bookshelf
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Branching: branching.md
  - Workflow: 
    - Workflow: workflow.md
    - Pull Request: pull-request.md
use_directory_urls: false