site_name: Central Docs
repo_url: https://github.com/city-of-saint-louis/central-docs
theme: 
  name: material
  icon:
    logo: material/bookshelf
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Branching: branching.md
  - Workflow: workflow.md