site_name: Central Docs
site_url: https://city-of-saint-louis.github.io/central-docs/
repo_url: https://github.com/city-of-saint-louis/central-docs
repo_name: /central-docs
theme: 
  name: material
  favicon: assets/bookshelf.svg
  icon:
    logo: material/bookshelf
    repo: fontawesome/brands/github
  features:
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - open-in-new-tab:
      add_icon: true
nav:
  - Home: index.md
  - Style Guides:
    - ColdFusion: style-guide-coldfusion.md
    - HTML/CSS: style-guide-html-css.md
    - JavaScript: style-guide-javascript.md
    - Python: style-guide-python.md
    - SQL: style-guide-sql.md
    - TypeScript: style-guide-typescript.md 
  - Workflow: 
    - Workflow: workflow.md
    - Branching: branching.md
    - Pull Request: pull-request.md
    - Code Review: code-review.md
  - External Resources: external-resources.md
use_directory_urls: false